### ISSUE TITLE
Received data from unknown peer

### ISSUE THREAD

**Issue by TripleA150** [GubernievS/AntiZapret-VPN#12]
Здравствуйте. Вылезает такая ошибка в консоле, что с ней можно сделать?
![image](https://github.com/user-attachments/assets/c5b64f9e-e2bc-4f7a-98c9-3bb3bdf827ff)

**Comment by GubernievS** [comment]
Судя по всему это появляется из-за DCO
Можно отписать им сюда
https://github.com/OpenVPN/ovpn-dco/issues
