### ISSUE TITLE
Каким образом поменять ip адреса ?

### ISSUE THREAD

**Issue by Eleafan** [GubernievS/AntiZapret-VPN#13]
можно ли изменить адреса 
DNS антизапрета = 10.29.0.1 
AntiZapret VPN = 10.29.0.0/16
Обычный VPN = 10.28.0.0/16
Подменные IP = 10.30.0.0/15

на другие? и как это сделать лучше всего

**Comment by GubernievS** [comment]
Самый простой способ - при установке скрипт предлагает использование альтернативных адресов на 172... вместо 10...
