### ISSUE TITLE
Ошибка при установке на Ubuntu ("не находит релизные файлы")

### ISSUE THREAD

**Issue by SharkTPO** [GubernievS/AntiZapret-VPN#14]
На сервере под:
![изображение](https://github.com/user-attachments/assets/0edc89e6-6d98-4451-bdab-c16b41665192)
При задании первой команды на установку (от apt update && ...) возникает следующая проблема:
![изображение](https://github.com/user-attachments/assets/4f1abe29-05a6-4013-8bd1-1b07ff76abc3)
При исключении "apt update" - установка проходит по плану (до опции задания диапазона дефолтных ip-адресов), а потом завершается с ошибкой:
![изображение](https://github.com/user-attachments/assets/6e46a900-d0e3-4bb2-b718-b67b35a79799)

При этом, ставил на соседний VPS - аналогичный - никаких проблем и все звезды сошлись.

**Comment by GubernievS** [comment]
Проблема с не относящимся к антизапрету репозиторием Ookla Speedtest CLI - удалите его вручную или переустановите систему и ставьте скрипт на чистую ОС

**Comment by SharkTPO** [comment]
Понял. Спасибо!
