### ISSUE TITLE
Error occurred at line 246 while executing: /root/antizapret/parse.sh ips

### ISSUE THREAD

**Issue by NotSBad** [GubernievS/AntiZapret-VPN#15]
Parse blocked ips
Blocked ips: 3 result/blocked-ips.txt
Restart ferm
/root/antizapret/parse.sh: line 107: =true: command not found

Error occurred at line 246 while executing: /root/antizapret/parse.sh ips

Debian 12

**Comment by GubernievS** [comment]
Исправил

**Comment by NotSBad** [comment]
> Исправил

Спасибо. К серверу после перезагрузки подключиться не могу теперь.

**Comment by GubernievS** [comment]
Скрипт интерфейсы не трогает

**Comment by NotSBad** [comment]
> Исправил

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Parse blocked ips
Blocked ips: 3 result/blocked-ips.txt
Restart ferm
cp: cannot stat 'result/blocked-hosts.conf': No such file or directory

Error occurred at line 246 while executing: /root/antizapret/parse.sh ips

**Comment by GubernievS** [comment]
ну вроде все поправил
