### ISSUE TITLE
Папка для установки

### ISSUE THREAD

**Issue by JoyZzzzz** [GubernievS/AntiZapret-VPN#17]
Не очень удобно когда скрипт создает папки и файлы в корне root, возможно ли скрипту указать куда устанавливаться?
Например чтобы все было в папке /root/antizapret-vpn/*

**Comment by GubernievS** [comment]
В планах переделать и привести в порядок папки в root - сделать папку antizapret с файлами антизапрета и папку для профилей vpn подключений
Указывать куда ставить возможности нет и не планируется

**Comment by GubernievS** [comment]
Сделал
