### ISSUE TITLE
Подружить Amnezia и Antizapret.

### ISSUE THREAD

**Issue by blablacar12345** [GubernievS/AntiZapret-VPN#18]
Привет. Как-то можно подружить amnezia и antizapret? Хотел самостоятельно накатить Amnezia через мобильное приложение, чтобы мог установить протокол XRAY, но после установки antizapret невозможно это сделать. В логе docker.service вот это.
```

Nov 10 16:27:57 v173994104.local dockerd[11337]: time="2024-11-10T16:27:57.767857184Z" level=info msg="Loading containers: start."
Nov 10 16:27:58 v173994104.local dockerd[11337]: time="2024-11-10T16:27:58.011287956Z" level=info msg="Loading containers: done."
Nov 10 16:27:58 v173994104.local dockerd[11337]: time="2024-11-10T16:27:58.049168437Z" level=info msg="Docker daemon" commit=24.0.7-0ubuntu4.1 graphdriver=overlay2 version=24.0.7
Nov 10 16:27:58 v173994104.local dockerd[11337]: time="2024-11-10T16:27:58.049630935Z" level=info msg="Daemon has completed initialization"
Nov 10 16:27:58 v173994104.local dockerd[11337]: time="2024-11-10T16:27:58.097657310Z" level=info msg="API listen on /run/docker.sock"
Nov 10 16:27:58 v173994104.local systemd[1]: Started docker.service - Docker Application Container Engine.
Nov 10 16:28:20 v173994104.local dockerd[11337]: time="2024-11-10T16:28:20.634116150Z" level=info msg="Layer sha256:8abce082fa968ed89ea792e4d8bc8aafe05edd427c90e1d7ace5de7f37c769be cleaned up"
Nov 10 16:28:31 v173994104.local dockerd[11337]: time="2024-11-10T16:28:31.011253534Z" level=info msg="ignoring event" container=91174a0c33f382b3ee9fde8bb45a94801ba37a7228377968ca1cff8a6e92ab44 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Nov 10 16:28:33 v173994104.local dockerd[11337]: time="2024-11-10T16:28:33.066172050Z" level=error msg="Not continuing with pull after error: errors:\ndenied: requested access to the resource is denied\nunauthorized: authentication required\n"
Nov 10 16:28:33 v173994104.local dockerd[11337]: time="2024-11-10T16:28:33.066228249Z" level=info msg="Ignoring extra error returned from registry" error="unauthorized: authentication required"
```

При попытке раскатать через docker-compose вот это:

```
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/noble/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/noble-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/noble-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/noble-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

```

Явно проблема в DNS, но не совсем понимаю каким-образом не ломая antizapret исправить проблему.

**Comment by GubernievS** [comment]
Привет, для работы 443 порта на сервере надо отключить использование порта у openvpn в /etc/ferm/ferm.conf
Про днс - антизапрет не меняет настройки днс, разве что на сервере отключается ipv6 через настройку /etc/sysctl.d/20-network.conf и если днс есть только по ipv6 - он не работает
С докером от амнезии, или с другими я не тестировал

**Comment by blablacar12345** [comment]
Я 443 порт как альтернативный не использовал. Тут в целом вопрос почему после setup.sh невозможно поднять контейнер через docker-compose. Возможно это можно записать в баги. Хотелось бы протестировать по возможности.

А планируется ли облегченная версия сборки только под openvpn?

**Comment by GubernievS** [comment]
Я ж говорю, возможно отключение ipv6 ломает днс, если днс на сервере только по ipv6 прописаны, на 4пда было обсуждение и в 1 сообщение ссылка на починку, может быть добавлю в скрипт автоматически исправление днс

Делать разные версии не планирую

**Comment by blablacar12345** [comment]
А как проверить прописаны по ipv6 или по ipv4?
В resolv.conf стоят гугловые dns по ipv4

**Comment by GubernievS** [comment]
командой resolvectl

**Comment by blablacar12345** [comment]
О, проверю. В чем проблема была?

**Comment by GubernievS** [comment]
Если просто то теперь два вида iptables и они разные, а ferm блокирует правила из нового iptables, сохраняю теперь при установке для ferm новые правила (где прописаны для докера) и ferm их не ломает

**Comment by blablacar12345** [comment]
> Подружил, ставишь амнезию, потом антизапрет

А у меня почему-то не работает. Была предустановлена Amnezia. Поставил zapret и все. Подключение говорит активное (указывает приложение), но ничего не резолвится от слова совсем)

**Comment by GubernievS** [comment]
Хм, а ты амнезию настроил до установки антизапрета?

попробуй выполнить
`import-ferm > /etc/ferm/iptables.conf`
и ребутни сервер

**Comment by GubernievS** [comment]
Подружил!

**Comment by blablacar12345** [comment]
> Подружил!

Что по итогу было?)
И можно ли накатывать antizapret после установки уже Amnezia?
