### ISSUE TITLE
RTMP YouTube

### ISSUE THREAD

**Issue by TripleA150** [GubernievS/AntiZapret-VPN#19]
Сам не наблюдал, но знакомые сказали, что эти ресурсы не блочат, но в обход они включены и скорость урезается. Единственный способ их исключить - добавить в exclude hosts custom?

a.rtmp.youtube.com
b.rtmp.youtube.com

**Comment by GubernievS** [comment]
Нет, их не исключить если есть в исключениях домен выше, те youtube.com

**Comment by Plyha** [comment]
Наверное надо через какое то время исключить youtube, если у всех он будет работать.

вопрос: если я добавлю в exclude лист youtube, он не будет проксироваться через запрет?

**Comment by GubernievS** [comment]
Если везде разблокируют то конечно уберу, но видя происходящее шансов не много
Не будет

**Comment by GubernievS** [comment]
Вот все домены которые проксируются через впн для ютуба:

youtube.com
googlevideo.com
ytimg.com
ggpht.com
googleapis.com
gstatic.com
youtu.be
googleusercontent.com
