### ISSUE TITLE
Добавить возможность удалить патч для Openvpn

### ISSUE THREAD

**Issue by Plyha** [GubernievS/AntiZapret-VPN#20]
Спасибо вам большое за ваш труд!

При запуске скрипта согласился с установкой патча для openvpn. Было бы здорово, что бы была возможность ставить/удалять этот патч. К примеру у меня микротик не хочет с патчем подключаться по udp, при этом телефоны нормально подключаются.

**Comment by GubernievS** [comment]
Патч удаляется при переустановке, для микротика нужно выбирать 2-ой вариант патча

**Comment by Plyha** [comment]
Интересно, а если я запущу скрипт по установке патча и выберу 2 вариант, или надо переустановку делать?

**Comment by GubernievS** [comment]
Да, можно запустить скрипт и сменить тип патча

**Comment by Plyha** [comment]
К сожалению это не помогло для микротика. Жаль, что без переустановки патч не удаляется

**Comment by GubernievS** [comment]
Возможно проблема в настройках микротика
Добавил возможность удалить патч из patch-openvpn.sh

**Comment by Plyha** [comment]
Спасибо, хочу проверить, но у меня пункт не появился.

Choose a version of the anti-censorship patch for OpenVPN (UDP only):
    1) Strong     - Recommended by default
    2) Error-free - If the Strong patch causes a connection error on your device or Mikrotik router



Нужно сервер переустанавливать?)

**Comment by GubernievS** [comment]
Ну а как пункт появится если не обновить в ручную на сервере файл patch-openvpn.sh
Весь сервер обновлять не обязательно

**Comment by GubernievS** [comment]
не, обновляет только списки и алгоритм обработки списков

**Comment by Plyha** [comment]
Спасибо!
Удалил патч и udp заработал на микротике.

**Comment by Plyha** [comment]
Решено
