### ISSUE TITLE
LXC  \ LXD

### ISSUE THREAD

**Issue by drno88** [GubernievS/AntiZapret-VPN#25]
what is the reason for the impossibility of installation in lxd?
the original project runs there without problems...
I only need openVPN, is this possible? run in LXD?
What should be removed from the installation script?

**Comment by GubernievS** [comment]
remove WireGuard and OpenVPN DCO - maybe it's not fully supported in LXD, im not tested it

**Comment by drno88** [comment]
Всё сработало, спасибо!

Еще вопрос - може ли мы посадить обычный впн на  антизапрет? я правильно понимаю что надо подправить iptables-up.sh ?

**Comment by GubernievS** [comment]
Regular VPN is built-in
See files /root/vpn/vpn-*
