### ISSUE TITLE
How to enable full VPN?

### ISSUE THREAD

**Issue by historydev** [GubernievS/AntiZapret-VPN#3]
In lxc and docker, I changed the file /etc/ferm/ferm.conf, commented this line:
```
# interface vpn+ mod connmark mark 1 REJECT;
```
Added to the client config:

```
#Redirect ALL TO VPN
redirect-gateway def1 bypass-dhcp
```

And everything worked, but now with the same actions it does not work.

What do I need to do to get a full VPN?

**Comment by GubernievS** [comment]
For full OpenVpn, it is better to use: this https://github.com/angristan/openvpn-install

**Comment by historydev** [comment]
> For full OpenVpn, it is better to use this: https://github.com/angristan/openvpn-install

thanks
