### ISSUE TITLE
Unable to locate package openvpn-dco-dkms

### ISSUE THREAD

**Issue by vellrya** [GubernievS/AntiZapret-VPN#4]
Ubuntu 22.04.4 LTS

apt install openvpn-dco-dkms
Unable to locate package openvpn-dco-dkms

[Решение](https://openvpn.net/cloud-docs/tutorials/configuration-tutorials/connectors/operating-systems/linux/tutorial--learn-to-install-and-control-the-openvpn-3-client.html#:~:text=Installation%20for%20Debian%20and%20Ubuntu&text=Type%20the%20following%20command%20into,the%20OpenVPN%203%20Linux%20packages.):

```
sudo mkdir -p /etc/apt/keyrings && curl -fsSL https://packages.openvpn.net/packages-repo.gpg | sudo tee /etc/apt/keyrings/openvpn.asc
DISTRO=$(lsb_release -c | awk '{print $2}')
echo "deb [signed-by=/etc/apt/keyrings/openvpn.asc] https://packages.openvpn.net/openvpn3/debian $DISTRO main" | sudo tee /etc/apt/sources.list.d/openvpn-packages.list
sudo apt update
apt install openvpn-dco-dkms
```

Предварительно еще делал apt upgrade, возможно, это необязательно.

UPD. К сожалению, не вижу разницы, скорость сильно меньше той, что хотелось бы
UPD2. Устанавливается версия 2.5.9, а DCO поддерживается на 2.6.0 и выше, судя по всему

**Comment by vellrya** [comment]
mkdir -p /etc/apt/keyrings # directory does not exist on older releases
curl -fsSL https://swupdate.openvpn.net/repos/repo-public.gpg | gpg --dearmor > /etc/apt/keyrings/openvpn-repo-public.gpg

#В этой команде надо заменить данные в <> на актуальные для системы (получить автоматически?)
echo "deb [arch=<arch> signed-by=/etc/apt/keyrings/openvpn-repo-public.gpg] https://build.openvpn.net/debian/openvpn/<version> <osrelease> main" > /etc/apt/sources.list.d/openvpn-aptrepo.list

Where <arch> can be one of

amd64
arm64
Where <version> can be one of

stable: stable releases only - no alphas, betas or RCs
testing: latest releases, including alphas/betas/RCs
release/2.3: OpenVPN 2.3 releases
release/2.4: OpenVPN 2.4 releases, including alphas/betas/RCs
release/2.5: OpenVPN 2.5 releases, including alphas/betas/RCs
release/2.6: OpenVPN 2.6 releases, including alphas/betas/RCs
and <osrelease> depends your distribution:

buster (Debian 10.x)
bullseye (Debian 11.x)
bookworm (Debian 12.x)
focal (Ubuntu 20.04 LTS)
jammy (Ubuntu 22.04 LTS)
noble (Ubuntu 24.04 LTS)

Для 22.04:
echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/openvpn-repo-public.gpg] https://build.openvpn.net/debian/openvpn/stable jammy main" > /etc/apt/sources.list.d/openvpn-aptrepo.list

apt-get update && apt-get install openvpn

Обновляется, перезапускаем контейнеры 
systemctl restart openvpn-server@antizapret-udp
systemctl restart openvpn-server@antizapret-tcp

Смотрим логи, работает
journalctl -u openvpn-server@antizapret-udp
OpenVPN 2.6.12 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] [DCO]

**Comment by GubernievS** [comment]
Изначально пакеты easy-rsa и knot-resolver ставились из репозиториев разработчиков, но с knot-resolver были проблемы на Ubuntu 24
Сейчас в скрипте все пакеты ставятся из официального стабильного репозитория дистрибутива
Можно конечно опять в ручную ставить более новые версии, но гарантии что оно будет работать как надо я не дам, так что я думаю не стоит усложнять, а если нужен DCO проще переставить сервер на Ubuntu 24.04 или Debian 12 где идет идет OpenVpn 2.6+
