### ISSUE TITLE
OpenWRT client OpenVPN

### ISSUE THREAD

**Issue by Shatoth** [GubernievS/AntiZapret-VPN#5]
Не удаётся установить соединение на роутере с OpenWRT.
Нужна инструкция. Файл ovpn не подходит для роутера на OpenWRT

**Comment by GubernievS** [comment]
Посмотрите инструкцию по настройке антизапрета из докер-контейнера: https://github.com/xtrime-ru/antizapret-vpn-docker/blob/master/docs/guide_OpenWrt.md

**Comment by Shatoth** [comment]
Не помогло. Обратил внимание, что в системном журнале ругается на конфиг openvpn серверной части:
2 18:05:02 2024 daemon.err openvpn(antizapret)[8336]: Options error: Unrecognized option or missing or extra parameter(s) in [PUSH-OPTIONS]:3: block-outside-dns (2.5.8)
Буду благодарен, если подскажете как это побороть. Любую инфу по роутеру, версиям, пакетам готов предоставить.

**Comment by Shatoth** [comment]
Не знаю почему, но мне частично помогло вот это (Инструкция по настройке на роутерах Keenetic)
"Для того чтобы подключение antizapret-client-xxx.ovpn заработало как надо на роутерах Keenetic, надо в antizapret-client-xxx.ovpn дописать:

pull-filter ignore block-outside-dns
route 192.168.1.1"

Хотя у меня не кинетик, а ASUS прошитый на OpenWRT.
Буду копать дальше, потому что DNS от провайдера меня не совсем устраивают.
