### ISSUE TITLE
Проблемы в работе на мобильных устройствах в приложениях

### ISSUE THREAD

**Issue by denlycode** [GubernievS/AntiZapret-VPN#8]
Беспокоит проблема, которая есть уже на протяжении долгого времени, в том числе и в сегодняшнем обновлении. Она появляется иногда и не у всех, а также, только на мобильных устройствах. Чаще всего не работает приложение Instagram на iOS, просто ничего не грузит. При этом, если в этот-же момент зайти в Safari и вписать в поиск instagram.com, то там он откроется, проблема только в приложении. На ПК в браузере также всё ок. Проблема решается временем, но она довольно часто и долго появляется. Также, недавно появилась в ютуб приложении. Превью грузятся, видео вообще нет (без таймлайна, нету соединения с сокетом ютуба). Заметил, что в публичном Antizapret VPN данной проблемы нет. Провайдер МГТС, мобильный оператор МТС (проблема наблюдается везде). Игрался всячески с DNS (менял дефолтный adguard, но на долго это проблему не решило).

**Comment by GubernievS** [comment]
Добавил одну опцию в kresd.conf. Попробуйте обновить на сервере в паке /etc/knot-resolver/ файл из https://github.com/GubernievS/AntiZapret-VPN/blob/main/setup/etc/knot-resolver/kresd.conf

Перезагрузитесь, понаблюдайте как будет вести себя, отпишитесь о результате
У меня нет яблочных устройств чтобы попробовать воспроизвести и проверить

**Comment by GubernievS** [comment]
Аналогично и для не запрещенных сайтов, запретил возвращать ipv6 с днс антизапрета
нужно еще обновить /etc/knot-resolver/kresd.conf из репозитория
https://github.com/GubernievS/AntiZapret-VPN/blob/main/setup/etc/knot-resolver/kresd.conf

По желанию добавить в ручную в файл адгуард днс:
policy.add(policy.all(policy.FORWARD({'94.140.14.14', '94.140.15.15'})))

Перезагрузите сервер и устройства, и понаблюдайте как будет вести себя не заблокированные сайты

**Comment by denlycode** [comment]
@GubernievS Спасибо большое за фидбэк, весь офис пользуется вашим решением. В течение недели отпишу сюда на счёт результатов.
