### ISSUE TITLE
Отлетел ютуб

### ISSUE THREAD

**Issue by denlycode** [GubernievS/AntiZapret-VPN#9]
Сейчас резко перестал ютуб работать, даже на GoodbueDPI. Превью грузит, видео вообще нет, с ПК тоже.

**Comment by denlycode** [comment]
Также, затестив ласт версию, получил ещё проблему, что оно отбрасывает 80% пакетов на сайтах. Если просто перезагружать одну и ту же страницу 5 раз, то 4 раза выдаст DNS ошибку, на 5 раз загрузит половину контента.
![image](https://github.com/user-attachments/assets/25669819-8fb8-49de-b0e9-6bb320bb6885)

**Comment by GubernievS** [comment]
Какая ос?

**Comment by GubernievS** [comment]
не, я про сервер, что там стоит?

**Comment by denlycode** [comment]
@GubernievS Ubuntu 22.04 чистая

**Comment by GubernievS** [comment]
проверил, поставил чистую 22, скрипт - все ок
[antizapret-client-188.130.206.216-udp.ovpn.txt](https://github.com/user-attachments/files/16985834/antizapret-client-188.130.206.216-udp.ovpn.txt)
расширение поменяйте
проверьте

**Comment by GubernievS** [comment]
Дополнительно выключил DNSSEC validation, может с этим проблема

**Comment by denlycode** [comment]
@GubernievS 
Хм, попробовал ваш конфиг, но всё та-же проблема, с разных и чистых браузеров пробовал, и, вроде, ни у одного меня такая проблема на ПК. Наблюдал на телефоне, этого не было, GoodbueDPI тоже работает.

**Comment by GubernievS** [comment]
А что именно не работает? В днс прописан адгуард, он режет всякую рекламу и прочее по днс, так что это возможно что что то не загрузилось тк было заблокировано

**Comment by denlycode** [comment]
@GubernievS  Ещё раз объясню. При попытке открыть любой сайт в браузере ошибка ERR_NAME_NOT_RESOLVED. И если просто при этой ошибки в тупую 5 раз один и тот-же сайт обновить, то 4 раза получишь ошибку, а на 5 он прогрузится, но как показал анализ пакетов из консоли - грузится не всё, а только 20-30% пакетов. Например, пропустил он главный HTML пакет, но не пропустил половину картинок. И это на любых сайтах в абсолютно случайном порядке, в другой раз, к примеру, это бы прогрузилось. Даже если хочу сейчас отправить коммент на гите, нажму пару раз на кнопку, получу ошибку, но раза с 5 оно пройдёт.

**Comment by GubernievS** [comment]
На моем впне это воспроизводится?

**Comment by denlycode** [comment]
@GubernievS Да.

**Comment by vellrya** [comment]
@denlycode, попробуйте для эксперимента закомментировать строку policy.add(policy.all(policy.FORWARD({'94.140.14.14', '94.140.15.15'})))" в файле /etc/knot-resolver/kresd.conf, чтобы стало 

`-- policy.add(policy.all(policy.FORWARD({'94.140.14.14', '94.140.15.15'})))`
(посмотрите пример других комментариев в этом файле). 

После чего выполните команду `systemctl restart kresd@1`
Очистите кеш днс на винде командой `ipconfig /flushdns`, полностью закройте хром, откройте заново и посмотрите, станут ли сайты открываться не с пятого раза.

**Comment by GubernievS** [comment]
Если у меня с этого сервера все нормально работает, то я думаю какая то проблема у вас
Попробуйте новую версию скачать
https://openvpn.net/client/client-connect-vpn-for-windows/

**Comment by GubernievS** [comment]
Ну давайте, убрал днс от адгуарда - ребутнул - проверяйте
Теперь днс от гугла 8.8.8.8

**Comment by denlycode** [comment]
@GubernievS Попробовал сейчас на вашем ВПНЕ, проблему это не решило.
Из того, что ещё наблюдал - вот вчера вечером и до раннего утра у всех абсолютно (т.е. уже более 10 человек, вне зависимости от платформы) отвалился ютуб, инста работает, превью грузятся с аватарками, сами видео нет (не появляется таймлайн), и проблема наблюдалась уже много раз, решается сама собой. Как появляется у всех, так и убирается у всех через время.

**Comment by galart404** [comment]
Появилась такая же проблема на двух разных VPS:
[antizapret-client-185.23.238.82-udp.ovpn.txt](https://github.com/user-attachments/files/16993731/antizapret-client-185.23.238.82-udp.ovpn.txt)
[antizapret-client-94.228.161.113-udp.ovpn.txt](https://github.com/user-attachments/files/16993748/antizapret-client-94.228.161.113-udp.ovpn.txt)

На первом отключил Адгуард как написал @vellrya но никаких изменений.
Можете протестировать и отписать работает/не работает.

Конфиг предоставленный @GubernievS у меня работает как положено, но Ютуб поставил страну Гонконг и включил рекламу. Через мой предоставленный второй конфиг Ютуб ставил Россию и рекламы не было и всё грузилось, раньше я думал, что это благодаря Адгуарду, но как я понимаю это не так.

**Comment by denlycode** [comment]
Дополнение к проблеме с ютубом из прошлого моего коммента:
Сейчас она снова появилась. Если проблема с сайтами наблюдается только на ПК, то проблема с ют наблюдается на любых платформах, сайтах и прочего). Он грузит всё, но как раз домен googlevideo.com отлетает с ошибкой (failed)net::ERR_NAME_NOT_RESOLVED. И забавно, что он продолжает пробовать подключаться 5 раз, получая ошибку, а где-то с шестого всё-таки законнектится к сокету и можно будет посмотреть видео. Не думаю, что это как-либо с AdGuard связано, ибо ошибки от адблокера я не получал нигде, да и всегда всё тестил с разными DNS. Я считаю, что ошибка как-то связана с ipV6, о которой вы писали на счёт инстагрмма, т.е. он много раз пытается получить ответ от DNS, и в конечном счёте он его получит. Также, та-же проблема с ютубом, только на абсолютно любые сайты, как я и говорил раннее, наблюдается у меня на ПК. Получаю ошибку от DNS, 5 раз перезагружаю сайт и в итоге можно его загрузить, но процентов 30 контента отпадает по той-же проблеме.
![image](https://github.com/user-attachments/assets/ff00550e-8b7b-4859-afd7-30feadc1710c)

**Comment by GubernievS** [comment]
А проблемы с ютбом - вы не через роутер сидите? Какой клиент openvpn?

Какиех нибудь адгуард днс на роутере нет?

185.23.238.82-udp.ovpn
94.228.161.113-udp.ovpn
у меня не подключаются

**Comment by galart404** [comment]
> А проблемы с ютбом - вы не через роутер сидите? Какой клиент openvpn?
> 
> Какиех нибудь адгуард днс на роутере нет?
> 
> 185.23.238.82-udp.ovpn 94.228.161.113-udp.ovpn у меня не подключаются

Подключался через роутер и официальный клиент OpenVPN на windows и андроид, везде проблема как у @denlycode - сайты загружались не с первого раза, а теперь и вовсе ничего не грузится т. к. ВПН либо не подключается либо соединение прерывается (в openvpn клиенте крутится индикатор подключения).

Адгуард ДНС нигде не прописаны.

Устанавливал на VPS чистый OpenVPN через панель на хостинге - всё работает.

**Comment by GubernievS** [comment]
@galart404 если сервера заблокированы, запустите: chmod +x patch-openvpn.sh && ./patch-openvpn.sh

как пропатчите, напишите - подключусь, сравню работу с тем же antizapret-client-188.130.206.216-udp.ovpn, что выкладывал ранее

**Comment by galart404** [comment]
> @galart404 если сервера заблокированы, запустите: chmod +x patch-openvpn.sh && ./patch-openvpn.sh
> 
> как пропатчите, напишите - подключусь, сравню работу с тем же antizapret-client-188.130.206.216-udp.ovpn, что выкладывал ранее

Пропатчил оба сервера - один очень медленно заблокированные сайты грузит (ютуб не может прогрузить), другой не подключается.

Если нужно, могу предоставить данные для доступа к серверам по ssh и/или к хостингам.

**Comment by GubernievS** [comment]
@galart404 можно глянуть
если зарегистрированы тут то напишите https://ntc.party/u/tyman

**Comment by galart404** [comment]
@GubernievS В данный момент и у меня работает, так уже было, потом через время снова сломалось, не понимаю с чем эти перебои связяны. Не подскажете, что со вторым сервером сделать можно, почему к нему не подключается?

Не разабрался как вам здесь https://ntc.party/u/tyman написать, в каком разделе.

Спасибо за помощь!

**Comment by GubernievS** [comment]
@galart404 поищите кнопку личные сообщения или что то типа того

если проблема только с загрузкой ютуба, то в момент проблем, откройте ссылку: https://redirector.googlevideo.com/report_mapping?di=no
запишите что там будет

сейчас там
185.23.238.82 => qsc-cgn1 (185.23.238.0/24)
cgn ближайший аэропорт к дата центру ютуба

**Comment by GubernievS** [comment]
94.228.161.113 возможно в блоке, возможно в блоке порт по протоколу udp (у меня такое было - атака на соседний хост а блок на всю подсеть)

**Comment by galart404** [comment]
> 94.228.161.113 возможно в блоке, возможно в блоке порт по протоколу udp (у меня такое было - атака на соседний хост а блок на всю подсеть)

Я на него чистый OpenVPN через панель на хостинге ставил - всё работало. Просто через этот сервер рекламы на ютубе нет, не знаю как так.

**Comment by galart404** [comment]
> 94.228.161.113 возможно в блоке, возможно в блоке порт по протоколу udp (у меня такое было - атака на соседний хост а блок на всю подсеть)

Подключился по TCP протоколу - работает! А кто что опять блокирует, это временно?

Ещё интересно, почему через этот сервер нет рекламы на ютуб (не меняется регион)

**Comment by denlycode** [comment]
@GubernievS Только вернулся с работы. Немного не понял, что в итоге можно сделать. ВПН у меня не на роутере, а на VDS, сижу через официальный Open VPN 3.5.0. Проблем с подключением/прерыванием самого ВПН по любым протоколам у меня никогда НЕ было, провайдер также ничего не блокирует. Есть вот эта проблема, которую описывал сообщениями выше про загрузку любых сайтов с 5 раза.

**Comment by Gruven** [comment]
Возможно немного не по теме, но себе и маме ставил оригинальный антизапрет (не с этого репозитория) на кинетик. Ошибка `ERR_NAME_NOT_RESOLVED` у меня появлялась при перезагрузке роутера, требовалось переподключить впн, а у мамы выдавало постоянно - пришлось убрать. Конфиг один и тот же, роутеры одинаковые, но провайдеры разные.

**Comment by GubernievS** [comment]
@Gruven, да, не по теме но я видел подобное поведение
Это ошибка разрешения имени сервера публичного антизапрета в стрчке "remote v.31337.lol"
Скорее всего это кинетика
Как я понял, решается либо добавлением на кинетик DNS-over-HTTPS или DNS-over-TLS
Либо заменой имени на ip так:
удаляем строку: remote v.31337.lol
добавляем строки:
remote-random
remote 51.158.187.25
remote 51.158.181.161
remote 51.75.75.245
remote 51.158.181.228
remote 51.75.70.203
remote 51.158.176.255
remote 141.95.17.71

**Comment by Gruven** [comment]
> Это ошибка разрешения имени сервера публичного антизапрета в строчке "remote v.31337.lol"

Я использую свой VPS, без домена

> Скорее всего это баг кинетика

Возможно, но странно, что отличия только в провайдере, а ошибка на одном есть, на другом нет

**Comment by GubernievS** [comment]
@Gruven Я подумал что ошибка ERR_NAME_NOT_RESOLVED на кинетике в логах при подключении к оригинальному антизапрету

Ну попробуйте с 0 поставить из этого репозитория и настроить кинетик по инструкции

**Comment by Gruven** [comment]
@GubernievS 
Проблема, описанная мной несколькими сообщениями выше, и, вероятно, проблема @denlycode связана с тем, что иногда DNS запросы (порт 53) отправляются по TCP, а не UDP, но в iptables [прописан только UDP](https://github.com/GubernievS/AntiZapret-VPN/blob/b8b00816a84c33ed5317afe427705e5b2f62f6ae/setup/root/antizapret/iptables-up.sh#L77).

Я вашим репозиторием не пользуюсь, но решил отписаться, т.к. потратил много времени на поиск причины.
